import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "./Navigation/NavBar";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Andrew Grant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={montserrat.className} lang="en" suppressHydrationWarning>
      {/* <head /> */}
      <body className="mx-auto relative">
      <NavBar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
