import type { Metadata } from "next";
// import { Kanit } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Andrew Grant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="text-text">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
